// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transport/shared/shared.proto

package msg_cyto_shared

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DiscordWorkRequest struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 string               `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Command              string               `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	ChannelID            string               `protobuf:"bytes,4,opt,name=channelID,proto3" json:"channelID,omitempty"`
	GuildID              string               `protobuf:"bytes,5,opt,name=guildID,proto3" json:"guildID,omitempty"`
	UserID               string               `protobuf:"bytes,6,opt,name=userID,proto3" json:"userID,omitempty"`
	SourceID             string               `protobuf:"bytes,7,opt,name=sourceID,proto3" json:"sourceID,omitempty"`
	Payload              map[string]string    `protobuf:"bytes,8,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MessageID            string               `protobuf:"bytes,9,opt,name=messageID,proto3" json:"messageID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DiscordWorkRequest) Reset()         { *m = DiscordWorkRequest{} }
func (m *DiscordWorkRequest) String() string { return proto.CompactTextString(m) }
func (*DiscordWorkRequest) ProtoMessage()    {}
func (*DiscordWorkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dd35d3e2549cbf4, []int{0}
}

func (m *DiscordWorkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscordWorkRequest.Unmarshal(m, b)
}
func (m *DiscordWorkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscordWorkRequest.Marshal(b, m, deterministic)
}
func (m *DiscordWorkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscordWorkRequest.Merge(m, src)
}
func (m *DiscordWorkRequest) XXX_Size() int {
	return xxx_messageInfo_DiscordWorkRequest.Size(m)
}
func (m *DiscordWorkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscordWorkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscordWorkRequest proto.InternalMessageInfo

func (m *DiscordWorkRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *DiscordWorkRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DiscordWorkRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *DiscordWorkRequest) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *DiscordWorkRequest) GetGuildID() string {
	if m != nil {
		return m.GuildID
	}
	return ""
}

func (m *DiscordWorkRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *DiscordWorkRequest) GetSourceID() string {
	if m != nil {
		return m.SourceID
	}
	return ""
}

func (m *DiscordWorkRequest) GetPayload() map[string]string {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *DiscordWorkRequest) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func init() {
	proto.RegisterType((*DiscordWorkRequest)(nil), "msg.cyto.shared.DiscordWorkRequest")
	proto.RegisterMapType((map[string]string)(nil), "msg.cyto.shared.DiscordWorkRequest.PayloadEntry")
}

func init() { proto.RegisterFile("transport/shared/shared.proto", fileDescriptor_9dd35d3e2549cbf4) }

var fileDescriptor_9dd35d3e2549cbf4 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x24, 0x4d, 0xbf, 0xf2, 0x2a, 0x28, 0x0f, 0x91, 0x25, 0x28, 0x16, 0x4f, 0x3d, 0x6d, 0xa5,
	0x5e, 0x4a, 0xcf, 0xf1, 0x10, 0x4f, 0x12, 0x04, 0xcf, 0xdb, 0x64, 0x4d, 0x4b, 0xb3, 0xd9, 0xb8,
	0x1f, 0x42, 0xfe, 0x84, 0xbf, 0x59, 0xb2, 0xdb, 0xb4, 0xa2, 0xa7, 0x7d, 0x33, 0xf3, 0x66, 0xf6,
	0x31, 0x70, 0x67, 0x14, 0xab, 0x75, 0x23, 0x95, 0x59, 0xea, 0x1d, 0x53, 0xbc, 0x38, 0x3e, 0xb4,
	0x51, 0xd2, 0x48, 0xbc, 0x14, 0xba, 0xa4, 0x79, 0x6b, 0x24, 0xf5, 0x74, 0x7c, 0x5f, 0x4a, 0x59,
	0x56, 0x7c, 0xe9, 0xe4, 0xad, 0xfd, 0x58, 0x9a, 0xbd, 0xe0, 0xda, 0x30, 0xd1, 0x78, 0xc7, 0xc3,
	0x77, 0x08, 0x98, 0xec, 0x75, 0x2e, 0x55, 0xf1, 0x2e, 0xd5, 0x21, 0xe3, 0x9f, 0x96, 0x6b, 0x83,
	0x6b, 0x88, 0x4e, 0x9b, 0x24, 0x98, 0x07, 0x8b, 0xd9, 0x2a, 0xa6, 0x3e, 0x8b, 0xf6, 0x59, 0xf4,
	0xad, 0xdf, 0xc8, 0xce, 0xcb, 0x88, 0x30, 0x34, 0x6d, 0xc3, 0xc9, 0x60, 0x1e, 0x2c, 0xa2, 0xcc,
	0xcd, 0x48, 0x60, 0x92, 0x4b, 0x21, 0x58, 0x5d, 0x90, 0xd0, 0xd1, 0x3d, 0xc4, 0x5b, 0x88, 0xf2,
	0x1d, 0xab, 0x6b, 0x5e, 0xa5, 0x09, 0x19, 0x3a, 0xed, 0x4c, 0x74, 0xbe, 0xd2, 0xee, 0xab, 0x22,
	0x4d, 0xc8, 0xc8, 0xfb, 0x8e, 0x10, 0x6f, 0x60, 0x6c, 0x35, 0x57, 0x69, 0x42, 0xc6, 0x4e, 0x38,
	0x22, 0x8c, 0x61, 0xaa, 0xa5, 0x55, 0x39, 0x4f, 0x13, 0x32, 0x71, 0xca, 0x09, 0xe3, 0x0b, 0x4c,
	0x1a, 0xd6, 0x56, 0x92, 0x15, 0x64, 0x3a, 0x0f, 0x17, 0xb3, 0xd5, 0x23, 0xfd, 0x53, 0x17, 0xfd,
	0xdf, 0x04, 0x7d, 0xf5, 0x96, 0xe7, 0xda, 0xa8, 0x36, 0xeb, 0x03, 0xba, 0xbb, 0x05, 0xd7, 0x9a,
	0x95, 0xdd, 0x47, 0x91, 0xbf, 0xfb, 0x44, 0xc4, 0x1b, 0xb8, 0xf8, 0x6d, 0xc3, 0x2b, 0x08, 0x0f,
	0xbc, 0x75, 0x3d, 0x46, 0x59, 0x37, 0xe2, 0x35, 0x8c, 0xbe, 0x58, 0x65, 0xfb, 0x9a, 0x3c, 0xd8,
	0x0c, 0xd6, 0xc1, 0x76, 0xec, 0xea, 0x7d, 0xfa, 0x09, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xd9, 0x0b,
	0xc8, 0xea, 0x01, 0x00, 0x00,
}
