// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transport/manager/manager.proto

package msg_cyto_manager

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommandDefinition_PermissionLevel int32

const (
	CommandDefinition_USER      CommandDefinition_PermissionLevel = 0
	CommandDefinition_MODERATOR CommandDefinition_PermissionLevel = 1
	CommandDefinition_ADMIN     CommandDefinition_PermissionLevel = 2
	CommandDefinition_OWNER     CommandDefinition_PermissionLevel = 3
)

var CommandDefinition_PermissionLevel_name = map[int32]string{
	0: "USER",
	1: "MODERATOR",
	2: "ADMIN",
	3: "OWNER",
}

var CommandDefinition_PermissionLevel_value = map[string]int32{
	"USER":      0,
	"MODERATOR": 1,
	"ADMIN":     2,
	"OWNER":     3,
}

func (x CommandDefinition_PermissionLevel) String() string {
	return proto.EnumName(CommandDefinition_PermissionLevel_name, int32(x))
}

func (CommandDefinition_PermissionLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb234ff2faa2e0ff, []int{1, 0}
}

type UpdatedCommandConfigurations struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CommandDefinitions   []*CommandDefinition `protobuf:"bytes,2,rep,name=commandDefinitions,proto3" json:"commandDefinitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdatedCommandConfigurations) Reset()         { *m = UpdatedCommandConfigurations{} }
func (m *UpdatedCommandConfigurations) String() string { return proto.CompactTextString(m) }
func (*UpdatedCommandConfigurations) ProtoMessage()    {}
func (*UpdatedCommandConfigurations) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb234ff2faa2e0ff, []int{0}
}

func (m *UpdatedCommandConfigurations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatedCommandConfigurations.Unmarshal(m, b)
}
func (m *UpdatedCommandConfigurations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatedCommandConfigurations.Marshal(b, m, deterministic)
}
func (m *UpdatedCommandConfigurations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatedCommandConfigurations.Merge(m, src)
}
func (m *UpdatedCommandConfigurations) XXX_Size() int {
	return xxx_messageInfo_UpdatedCommandConfigurations.Size(m)
}
func (m *UpdatedCommandConfigurations) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatedCommandConfigurations.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatedCommandConfigurations proto.InternalMessageInfo

func (m *UpdatedCommandConfigurations) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *UpdatedCommandConfigurations) GetCommandDefinitions() []*CommandDefinition {
	if m != nil {
		return m.CommandDefinitions
	}
	return nil
}

type CommandDefinition struct {
	CommandID            string                            `protobuf:"bytes,1,opt,name=commandID,proto3" json:"commandID,omitempty"`
	Enabled              bool                              `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Triggers             []string                          `protobuf:"bytes,3,rep,name=triggers,proto3" json:"triggers,omitempty"`
	PermissionLevel      CommandDefinition_PermissionLevel `protobuf:"varint,4,opt,name=permissionLevel,proto3,enum=msg.cyto.manager.CommandDefinition_PermissionLevel" json:"permissionLevel,omitempty"`
	ParameterDefinitions []*CommandParameterDefinition     `protobuf:"bytes,5,rep,name=parameterDefinitions,proto3" json:"parameterDefinitions,omitempty"`
	LastModifiedUserID   string                            `protobuf:"bytes,6,opt,name=lastModifiedUserID,proto3" json:"lastModifiedUserID,omitempty"`
	LastModifiedDateUtc  *timestamp.Timestamp              `protobuf:"bytes,7,opt,name=lastModifiedDateUtc,proto3" json:"lastModifiedDateUtc,omitempty"`
	Description          string                            `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Unlisted             bool                              `protobuf:"varint,9,opt,name=unlisted,proto3" json:"unlisted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CommandDefinition) Reset()         { *m = CommandDefinition{} }
func (m *CommandDefinition) String() string { return proto.CompactTextString(m) }
func (*CommandDefinition) ProtoMessage()    {}
func (*CommandDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb234ff2faa2e0ff, []int{1}
}

func (m *CommandDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandDefinition.Unmarshal(m, b)
}
func (m *CommandDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandDefinition.Marshal(b, m, deterministic)
}
func (m *CommandDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandDefinition.Merge(m, src)
}
func (m *CommandDefinition) XXX_Size() int {
	return xxx_messageInfo_CommandDefinition.Size(m)
}
func (m *CommandDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_CommandDefinition proto.InternalMessageInfo

func (m *CommandDefinition) GetCommandID() string {
	if m != nil {
		return m.CommandID
	}
	return ""
}

func (m *CommandDefinition) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *CommandDefinition) GetTriggers() []string {
	if m != nil {
		return m.Triggers
	}
	return nil
}

func (m *CommandDefinition) GetPermissionLevel() CommandDefinition_PermissionLevel {
	if m != nil {
		return m.PermissionLevel
	}
	return CommandDefinition_USER
}

func (m *CommandDefinition) GetParameterDefinitions() []*CommandParameterDefinition {
	if m != nil {
		return m.ParameterDefinitions
	}
	return nil
}

func (m *CommandDefinition) GetLastModifiedUserID() string {
	if m != nil {
		return m.LastModifiedUserID
	}
	return ""
}

func (m *CommandDefinition) GetLastModifiedDateUtc() *timestamp.Timestamp {
	if m != nil {
		return m.LastModifiedDateUtc
	}
	return nil
}

func (m *CommandDefinition) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CommandDefinition) GetUnlisted() bool {
	if m != nil {
		return m.Unlisted
	}
	return false
}

type CommandParameterDefinition struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pattern              string   `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Optional             string   `protobuf:"bytes,3,opt,name=optional,proto3" json:"optional,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandParameterDefinition) Reset()         { *m = CommandParameterDefinition{} }
func (m *CommandParameterDefinition) String() string { return proto.CompactTextString(m) }
func (*CommandParameterDefinition) ProtoMessage()    {}
func (*CommandParameterDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb234ff2faa2e0ff, []int{2}
}

func (m *CommandParameterDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandParameterDefinition.Unmarshal(m, b)
}
func (m *CommandParameterDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandParameterDefinition.Marshal(b, m, deterministic)
}
func (m *CommandParameterDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandParameterDefinition.Merge(m, src)
}
func (m *CommandParameterDefinition) XXX_Size() int {
	return xxx_messageInfo_CommandParameterDefinition.Size(m)
}
func (m *CommandParameterDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandParameterDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_CommandParameterDefinition proto.InternalMessageInfo

func (m *CommandParameterDefinition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CommandParameterDefinition) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *CommandParameterDefinition) GetOptional() string {
	if m != nil {
		return m.Optional
	}
	return ""
}

func init() {
	proto.RegisterEnum("msg.cyto.manager.CommandDefinition_PermissionLevel", CommandDefinition_PermissionLevel_name, CommandDefinition_PermissionLevel_value)
	proto.RegisterType((*UpdatedCommandConfigurations)(nil), "msg.cyto.manager.UpdatedCommandConfigurations")
	proto.RegisterType((*CommandDefinition)(nil), "msg.cyto.manager.CommandDefinition")
	proto.RegisterType((*CommandParameterDefinition)(nil), "msg.cyto.manager.CommandParameterDefinition")
}

func init() { proto.RegisterFile("transport/manager/manager.proto", fileDescriptor_bb234ff2faa2e0ff) }

var fileDescriptor_bb234ff2faa2e0ff = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x41, 0x6f, 0x1a, 0x3d,
	0x10, 0xfd, 0x16, 0x48, 0xc2, 0x0e, 0xfa, 0x1a, 0xea, 0xf6, 0x60, 0xa1, 0x48, 0x59, 0xd1, 0xcb,
	0x1e, 0x2a, 0x23, 0x91, 0x4b, 0x8f, 0x8d, 0x58, 0x0e, 0x48, 0x21, 0x44, 0x4e, 0x50, 0x4f, 0x95,
	0x6a, 0xd8, 0xd9, 0x95, 0xa5, 0x5d, 0x7b, 0x65, 0x9b, 0x4a, 0xfd, 0x43, 0xbd, 0xf5, 0x3f, 0x56,
	0x6b, 0x58, 0x42, 0x09, 0x51, 0x7b, 0xb2, 0x67, 0xe6, 0xbd, 0xe7, 0xa7, 0xe7, 0x81, 0x6b, 0x67,
	0x84, 0xb2, 0x95, 0x36, 0x6e, 0x54, 0x0a, 0x25, 0x72, 0x34, 0xcd, 0xc9, 0x2a, 0xa3, 0x9d, 0x26,
	0xfd, 0xd2, 0xe6, 0x6c, 0xfd, 0xc3, 0x69, 0xb6, 0xeb, 0x0f, 0xae, 0x73, 0xad, 0xf3, 0x02, 0x47,
	0x7e, 0xbe, 0xda, 0x64, 0x23, 0x27, 0x4b, 0xb4, 0x4e, 0x94, 0xd5, 0x96, 0x32, 0xfc, 0x15, 0xc0,
	0xd5, 0xb2, 0x4a, 0x85, 0xc3, 0x74, 0xa2, 0xcb, 0x52, 0xa8, 0x74, 0xa2, 0x55, 0x26, 0xf3, 0x8d,
	0x11, 0x4e, 0x6a, 0x65, 0xc9, 0x27, 0x08, 0xf7, 0x1c, 0x1a, 0x44, 0x41, 0xdc, 0x1b, 0x0f, 0xd8,
	0x56, 0x95, 0x35, 0xaa, 0xec, 0xa9, 0x41, 0xf0, 0x67, 0x30, 0x79, 0x04, 0xb2, 0xde, 0x4a, 0x26,
	0x98, 0x49, 0x25, 0xbd, 0x1e, 0x6d, 0x45, 0xed, 0xb8, 0x37, 0xfe, 0xc0, 0x8e, 0xad, 0xb2, 0xc9,
	0x31, 0x96, 0x9f, 0xa0, 0x0f, 0x7f, 0x76, 0xe0, 0xed, 0x0b, 0x24, 0xb9, 0x82, 0x70, 0x87, 0x9d,
	0x25, 0xde, 0x64, 0xc8, 0x9f, 0x1b, 0x84, 0xc2, 0x05, 0x2a, 0xb1, 0x2a, 0x30, 0xa5, 0xad, 0x28,
	0x88, 0xbb, 0xbc, 0x29, 0xc9, 0x00, 0xba, 0xce, 0xc8, 0x3c, 0x47, 0x63, 0x69, 0x3b, 0x6a, 0xc7,
	0x21, 0xdf, 0xd7, 0xe4, 0x2b, 0x5c, 0x56, 0x68, 0x4a, 0x69, 0xad, 0xd4, 0xea, 0x0e, 0xbf, 0x63,
	0x41, 0x3b, 0x51, 0x10, 0xbf, 0x19, 0xdf, 0xfc, 0x83, 0x77, 0xf6, 0xf0, 0x27, 0x95, 0x1f, 0x6b,
	0x91, 0x6f, 0xf0, 0xbe, 0x12, 0x46, 0x94, 0xe8, 0xd0, 0x1c, 0xe6, 0x73, 0xe6, 0xf3, 0xf9, 0xf8,
	0xea, 0x1b, 0x0f, 0x2f, 0x49, 0xfc, 0xa4, 0x12, 0x61, 0x40, 0x0a, 0x61, 0xdd, 0x5c, 0xa7, 0x32,
	0x93, 0x98, 0x2e, 0x2d, 0x9a, 0x59, 0x42, 0xcf, 0x7d, 0x3a, 0x27, 0x26, 0xe4, 0x0e, 0xde, 0x1d,
	0x76, 0x13, 0xe1, 0x70, 0xe9, 0xd6, 0xf4, 0xe2, 0xaf, 0x7f, 0x7e, 0x8a, 0x46, 0x22, 0xe8, 0xa5,
	0x68, 0xd7, 0x46, 0x56, 0xb5, 0x1b, 0xda, 0xf5, 0xcf, 0x1e, 0xb6, 0xea, 0xf0, 0x37, 0xaa, 0x90,
	0xd6, 0x61, 0x4a, 0x43, 0xff, 0x2f, 0xfb, 0x7a, 0xf8, 0x19, 0x2e, 0x8f, 0x12, 0x24, 0x5d, 0xe8,
	0x2c, 0x1f, 0xa7, 0xbc, 0xff, 0x1f, 0xf9, 0x1f, 0xc2, 0xf9, 0x22, 0x99, 0xf2, 0xdb, 0xa7, 0x05,
	0xef, 0x07, 0x24, 0x84, 0xb3, 0xdb, 0x64, 0x3e, 0xbb, 0xef, 0xb7, 0xea, 0xeb, 0xe2, 0xcb, 0xfd,
	0x94, 0xf7, 0xdb, 0xc3, 0x0c, 0x06, 0xaf, 0x27, 0x46, 0x08, 0x74, 0x94, 0x28, 0x71, 0xb7, 0x2b,
	0xfe, 0x5e, 0xaf, 0x49, 0x25, 0x9c, 0x43, 0xa3, 0xfc, 0x9a, 0x84, 0xbc, 0x29, 0x6b, 0xa7, 0xda,
	0x7b, 0x16, 0x05, 0x6d, 0xfb, 0xd1, 0xbe, 0x5e, 0x9d, 0xfb, 0x40, 0x6e, 0x7e, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x91, 0xc9, 0x1e, 0x63, 0x9d, 0x03, 0x00, 0x00,
}
